# ==============================================================================
# SEED Labs 2.0 — Cross-Site Scripting (XSS) Attack Lab
#
# Official lab manual:
#   https://seedsecuritylabs.org/Labs_20.04/Web/Web_XSS_Elgg/
# ==============================================================================

services:

  elgg:
    build: ./image_www
    image: seed-image-www-xss-elgg
    container_name: elgg-10.9.0.5
    tty: true
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.5
    ports:
      - "10081:80"
    environment:
      - MYSQL_HOST=10.9.0.6

  mysql:
    build: ./image_mysql
    image: seed-image-mysql-xss-elgg
    container_name: mysql-10.9.0.6-xss
    restart: unless-stopped
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.6
    environment:
      - MYSQL_ROOT_PASSWORD=seedubuntu
    command: --default-authentication-plugin=mysql_native_password

networks:
  net-10.9.0.0:
    name: net-10.9.0.0-xss
    ipam:
      config:
        - subnet: 10.9.0.0/24
