# ==============================================================================
# SEED Labs 2.0 — Shellshock Vulnerability Lab
# ==============================================================================

services:

  www:
    build: ./image_www
    image: seed-image-www-shellshock
    container_name: shellshock-10.9.0.80
    tty: true
    restart: unless-stopped
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.80
    ports:
      - "10086:80"

networks:
  net-10.9.0.0:
    name: net-10.9.0.0-shellshock
    ipam:
      config:
        - subnet: 10.9.0.0/24
